### ISSUE TITLE
run.py file missing

### ISSUE THREAD

**Issue by QianpengLi577** [RuokaiYin/SATA_Sim#1]
When I run `inference-energy-cal/cycle-utils.py`,
I get this error
```
can't open file '....../scale-sim-v2/run.py': [Errno 2] No such file or directory".
```
Could you please provide this file？

In addition, I found a bug that doesn't affect the simulation results too much.
The `extract_workload` function in `energy-cal.py` calculates the size of the output feature map correctly only for the convolutional layers, but not for the fully-connected layers.
Here is the relevant code
```
of_w = (math.floor((attr['IFMAP Width'] + 2 - attr['Filter Width'])/attr['Strides']) + 1)
of_h = (math.floor((attr['IFMAP Height'] + 2 - attr['Filter Height'])/attr['Strides']) + 1)
```

**Comment by RuokaiYin** [comment]
Hi Qianpeng,

Sorry for resolving this issue a little bit late. My schedule has been quite overwhelming recently. I just added the scale sim files into another folder and changed all the relative paths. Please check whether it can be successfully running on your side. Please do let me know if there are any further issues, I will be happy to help.

Thank you for pointing out the stride bug, I will resolve it ASAP.

Best,
Ruokai

**Comment by QianpengLi577** [comment]
Hi Ruokai,

Thanks for fixing it, it works well now.

Best,
Qianpeng

**Comment by RuokaiYin** [comment]
The FC kernel is now supported. Thanks.
