### ISSUE TITLE
What each output refers to?

### ISSUE THREAD

**Issue by whz-snn** [RuokaiYin/SATA_Sim#2]
By modifying the contents of the workload.yml file, we get the results of computation-energy.yaml and memory-energy.yaml. But it's not clear what each output represents exactly, does the author have more details on this?

**Comment by RuokaiYin** [comment]
Hi,

The output of the memory-energy.yaml consists of the access energy of SRAM and DRAM for different components.
The output of the computation-energy.yaml consists of the energy cost of different computation units.

I will add some more explanations in the README.md. For now, you can first go to the SATA paper to get a basic idea of how those components contribute to the processing of SNNs on ASIC circuits. Thanks. Please let me know if there are further questions.
